### ISSUE TITLE
Bug in AmberToB.d

### ISSUE THREAD

**Issue by Nullset3** [RoxanneSHS/AmberEET#1]
You APPEND M#AMBERP when you should BEGIN M#AMB25P.

**Comment by RoxanneSHS** [comment]
Thank you. In deed that may create an issue in BG2EE. The ToB extension was tested in EET, so it never came to surface (EET merges the 25 dialogues into the BG2 ones).

**Comment by RoxanneSHS** [comment]
Corrected version uploaded.
